FROM maven:3.8.5-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml /app/
COPY src /app/src
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/usuarioapirest-0.0.1-SNAPSHOT.jar /app/usuario.jar
ENTRYPOINT ["java", "-jar", "/app/usuario.jar"]
